"""tests/test_isolation.py -- normal-path tenant isolation.

These tests prove the *well-behaved* half of the guarantee: when two tenants A
and B each own rows, a query run under tenant A's context returns only A's rows
and never B's -- even for ordinary queries that DO carry a `WHERE tenant_id`
clause, and even when a query explicitly asks for another tenant's rows.

(The "forgot the WHERE clause" pentest lives in test_break_isolation.py. Here we
show that the honest, filtered queries an application actually writes are
isolated by the database, so the app never has to trust itself to get the filter
right.)

How the pieces line up with the contract on disk:

  * SEEDING runs as the bootstrap superuser `postgres` (ADMIN_DSN). A superuser
    bypasses Row-Level Security entirely -- even under FORCE -- so seed rows for
    *both* tenants can be inserted from one connection without juggling the GUC.
    This is the leak/counter-example role; it is used here ONLY to set up data.

  * ASSERTIONS run as the non-owner application role `app_user` (APP_DSN),
    through the real application code path in app/db.py. That role is
    NOSUPERUSER + NOBYPASSRLS and does not own the tables, so the policies in
    migrations/002_rls.sql actually bind. A guard test below verifies this, so
    we can never accidentally "prove" isolation from a privileged connection.

  * The per-request tenant context is the `app.tenant_id` GUC, set by
    app.db.tenant_connection via set_config with the id bound as a parameter.

Requires a running Postgres with the migrations applied (`make up`). Override
APP_DSN / ADMIN_DSN via the environment; the defaults are the dev-only locals.
"""

import os
import sys
import uuid
from collections import namedtuple

import psycopg
import pytest

# Make the project root importable so we exercise the REAL application data
# layer (app/db.py) instead of re-implementing the connection logic here. This
# keeps the test honest -- it isolates exactly the way a request does -- without
# needing a shared conftest.py.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db import tenant_connection  # noqa: E402  (after sys.path setup)

# Superuser connection, used ONLY to seed/tear down data (bypasses RLS).
ADMIN_DSN = os.environ.get(
    "ADMIN_DSN", "postgresql://postgres:postgres@localhost:5432/rls_lab"
)

# What we seed. Asymmetric counts on purpose: if isolation were broken and a
# tenant saw everything, "A sees exactly its own two" would still fail loudly.
A_ITEM_NAMES = ["alpha-one", "alpha-two"]
B_ITEM_NAMES = ["bravo-one"]

Seed = namedtuple("Seed", ["a_id", "b_id", "a_names", "b_names"])


def _skip_if_db_unreachable(dsn):
    """Skip the module cleanly when no Postgres is reachable.

    A fresh checkout with no database should not error out: these tests require a
    running Postgres with the migrations applied (``make up``). This skips ONLY
    on a connection/operational failure -- never on an assertion -- so a genuine
    isolation regression can never hide behind a skip. When a database IS present
    the guard is a no-op and every assertion runs for real.
    """
    try:
        with psycopg.connect(dsn, connect_timeout=3) as probe:
            probe.execute("SELECT 1")
    except psycopg.OperationalError as exc:
        host = dsn.rsplit("@", 1)[-1]  # drop credentials before printing
        pytest.skip(
            f"no Postgres reachable at {host}: {exc.__class__.__name__}. "
            "Run `make up` (Docker) or point APP_DSN/ADMIN_DSN at a local "
            "Postgres with migrations/ applied."
        )


@pytest.fixture(scope="module")
def seed():
    """Create tenants A and B (with items) as the superuser, then clean up.

    Rows are inserted from the superuser connection because it bypasses RLS, so
    a single connection can stamp rows for both tenants. Ids are generated by the
    database and returned; names are tagged with a random suffix so repeat runs
    against a persistent database never collide. Teardown deletes both tenants;
    `items.tenant_id ... ON DELETE CASCADE` removes their items with them.
    """
    _skip_if_db_unreachable(ADMIN_DSN)
    tag = uuid.uuid4().hex[:8]
    with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
        a_id = admin.execute(
            "INSERT INTO tenants (name) VALUES (%s) RETURNING id",
            (f"tenant-A-{tag}",),
        ).fetchone()[0]
        b_id = admin.execute(
            "INSERT INTO tenants (name) VALUES (%s) RETURNING id",
            (f"tenant-B-{tag}",),
        ).fetchone()[0]
        for name in A_ITEM_NAMES:
            admin.execute(
                "INSERT INTO items (tenant_id, name) VALUES (%s, %s)", (a_id, name)
            )
        for name in B_ITEM_NAMES:
            admin.execute(
                "INSERT INTO items (tenant_id, name) VALUES (%s, %s)", (b_id, name)
            )

    try:
        yield Seed(a_id, b_id, A_ITEM_NAMES, B_ITEM_NAMES)
    finally:
        with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
            admin.execute(
                "DELETE FROM tenants WHERE id = ANY(%s)", ([a_id, b_id],)
            )


def test_app_connection_is_a_non_owner_non_bypass_role(seed):
    """Guard: the assertions below run as `app_user`, so RLS actually applies.

    A superuser or a BYPASSRLS/owner connection would silently see every row, and
    every isolation assertion in this file would then pass vacuously while proving
    nothing. Fail hard here if the app path is ever mis-wired to such a role.
    """
    with tenant_connection(str(seed.a_id)) as conn:
        who = conn.execute(
            "SELECT current_user AS role, current_setting('is_superuser') AS is_superuser"
        ).fetchone()
        bypasses_rls = conn.execute(
            "SELECT rolbypassrls FROM pg_roles WHERE rolname = current_user"
        ).fetchone()["rolbypassrls"]

    assert who["role"] == "app_user"
    assert who["is_superuser"] == "off"
    assert bypasses_rls is False


def test_tenant_a_filtered_query_returns_exactly_its_own_items(seed):
    """Under A's context, the normal `WHERE tenant_id = A` query returns A's rows."""
    with tenant_connection(str(seed.a_id)) as conn:
        rows = conn.execute(
            "SELECT id, tenant_id, name FROM items "
            "WHERE tenant_id = %s ORDER BY name",
            (seed.a_id,),
        ).fetchall()

    assert [r["name"] for r in rows] == sorted(seed.a_names)
    # Every row belongs to A, and none belongs to B.
    assert all(r["tenant_id"] == seed.a_id for r in rows)
    assert all(r["tenant_id"] != seed.b_id for r in rows)


def test_tenant_b_filtered_query_returns_exactly_its_own_items(seed):
    """Symmetric check: under B's context, B sees only B's rows."""
    with tenant_connection(str(seed.b_id)) as conn:
        rows = conn.execute(
            "SELECT id, tenant_id, name FROM items "
            "WHERE tenant_id = %s ORDER BY name",
            (seed.b_id,),
        ).fetchall()

    assert [r["name"] for r in rows] == sorted(seed.b_names)
    assert all(r["tenant_id"] == seed.b_id for r in rows)
    assert all(r["tenant_id"] != seed.a_id for r in rows)


def test_tenant_a_cannot_read_b_rows_even_when_it_asks_for_them(seed):
    """The strongest normal-query check: A explicitly filters for B's tenant_id.

    The `WHERE tenant_id = <B>` names B directly, yet the RLS USING clause pins
    visibility to A, so the rows never materialise. A cannot reach B's data even
    on purpose. (This is a filtered query -- the no-WHERE variant is the pentest
    in test_break_isolation.py.)
    """
    with tenant_connection(str(seed.a_id)) as conn:
        rows = conn.execute(
            "SELECT id, name FROM items WHERE tenant_id = %s",
            (seed.b_id,),
        ).fetchall()

    assert rows == []


def test_counts_are_scoped_to_the_active_tenant(seed):
    """Even an aggregate (which has no rows to eyeball) counts only A's rows."""
    with tenant_connection(str(seed.a_id)) as conn:
        a_seen = conn.execute(
            "SELECT count(*) AS c FROM items WHERE tenant_id = %s", (seed.a_id,)
        ).fetchone()["c"]
        # Counting B's items from inside A's context yields zero, not B's total.
        b_seen_from_a = conn.execute(
            "SELECT count(*) AS c FROM items WHERE tenant_id = %s", (seed.b_id,)
        ).fetchone()["c"]

    assert a_seen == len(seed.a_names)
    assert b_seen_from_a == 0


def test_tenants_table_is_self_isolated(seed):
    """The tenants table isolates on its own id: A sees its row, not B's.

    A normal filtered lookup for A's own tenant returns exactly one row; the same
    shape of query aimed at B's tenant returns nothing from inside A's context.
    """
    with tenant_connection(str(seed.a_id)) as conn:
        own = conn.execute(
            "SELECT id, name FROM tenants WHERE id = %s", (seed.a_id,)
        ).fetchall()
        other = conn.execute(
            "SELECT id, name FROM tenants WHERE id = %s", (seed.b_id,)
        ).fetchall()

    assert len(own) == 1
    assert own[0]["id"] == seed.a_id
    assert other == []
